"""
Reward wrapper with dynamic reward function replacement (Eureka-style).

Extends the base RewardWrapper to support:
1. YAML-based weighted rewards (original functionality)
2. LLM-generated custom reward functions (NEW: Eureka mode)

In Eureka mode, the entire reward computation can be replaced with
a custom function generated by LLM, allowing for complete reward redesign
beyond simple weight tuning.

Supported tasks: PickCube, PushCube, OpenCabinetDoor/Drawer, UnitreeG1PlaceAppleInBowl, AnymalC-Reach, PegInsertionSide, PushT
"""

import gymnasium as gym
import sapien
import torch
import traceback
from typing import Dict, Optional, Callable, Tuple


# Default weights per task
TASK_DEFAULTS = {
    "PickCube": {
        "w_reach": 1.0,
        "w_grasp": 1.0,
        "w_place": 1.0,
        "w_static": 1.0,
        "w_success": 5.0,
    },
    "PushCube": {
        "w_reach": 1.0,
        "w_push": 1.0,
        "w_z_keep": 1.0,
        "w_success": 4.0,
    },
    "OpenCabinetDoor": {
        "w_reach": 1.0,
        "w_open": 1.0,
        "w_static": 3.0,
        "w_success": 5.0,
    },
    "OpenCabinetDrawer": {
        "w_reach": 1.0,
        "w_open": 1.0,
        "w_static": 3.0,
        "w_success": 5.0,
    },
    "UnitreeG1PlaceAppleInBowl": {
        "w_reach": 1.0,
        "w_grasp": 1.0,
        "w_place": 1.0,
        "w_above_bowl": 4.0,
        "w_release": 1.0,
        "w_success": 8.0,
    },
    "AnymalC": {
        "w_reach": 2.0,
        "w_vel_z_penalty": 2.0,
        "w_ang_vel_penalty": 0.05,
        "w_contact_penalty": 1.0,
        "w_qpos_penalty": 0.05,
    },
    "PegInsertionSide": {
        "w_reach": 1.0,
        "w_grasp": 1.0,
        "w_pre_insertion": 3.0,
        "w_insertion": 5.0,
        "w_success": 10.0,
    },
    "PushT": {
        "w_rotation": 0.5,
        "w_position": 0.5,
        "w_tcp_guide": 0.05,
        "w_success": 3.0,
    },
    "PickCubePandaAllegro": {
        "w_reach": 1.0,
        "w_grasp": 1.0,
        "w_place": 1.0,
        "w_static": 1.0,
        "w_success": 5.0,
    },
    "RotateValve": {
        "w_contact": 1.0,
        "w_velocity": 4.0,
        "w_progress": 1.0,
    },
    "UnitreeG1TransportBox": {
        "w_face_box": 1.0,
        "w_grasp": 1.0,
        "w_transport": 1.0,
        "w_release": 1.0,
        "w_success": 5.0,
    },
}


def _resolve_task_id(env_id: str) -> str:
    """Extract task name from env_id (e.g. 'PickCube-v1' -> 'PickCube').

    Prefers longest matching key to avoid 'PickCube' matching before
    'PickCubePandaAllegro'.
    """
    name = env_id.split("-")[0]
    # Sort by key length descending so longer (more specific) keys match first
    for key in sorted(TASK_DEFAULTS.keys(), key=len, reverse=True):
        if key in name:
            return key
    raise ValueError(
        f"Unsupported task: {env_id}. "
        f"Supported: {list(TASK_DEFAULTS.keys())}"
    )


class RewardWrapperDynamic(gym.Wrapper):
    """
    Computes reward with support for dynamic function replacement (Eureka mode).

    Two modes of operation:
    1. **YAML mode (default)**: Uses task-specific weighted components
    2. **Custom function mode**: Uses LLM-generated reward function

    Works with ManiSkill GPU-parallel environments (batched tensors).
    Must be placed BEFORE ManiSkillVectorEnv in the wrapper chain.
    Use with reward_mode="none".
    """

    def __init__(
        self,
        env,
        env_id: str,
        weights: Optional[Dict[str, float]] = None,
        raise_on_custom_fn_error: bool = False,
    ):
        super().__init__(env)
        self.task_id = _resolve_task_id(env_id)
        self.weights = dict(TASK_DEFAULTS[self.task_id])
        if weights is not None:
            self.weights.update(weights)
        self._last_breakdown: Dict[str, float] = {}

        # Store initial non-success weight sum for normalization.
        # When LLM changes weights, we scale the reward so its magnitude
        # stays consistent with the initial scale (prevents PPO instability).
        self._initial_component_sum = self._component_weight_sum()

        # Select YAML-based compute function
        self._compute_fn = {
            "PickCube": self._compute_pick_cube,
            "PushCube": self._compute_push_cube,
            "OpenCabinetDoor": self._compute_open_cabinet,
            "OpenCabinetDrawer": self._compute_open_cabinet,
            "UnitreeG1PlaceAppleInBowl": self._compute_unitree_place_apple,
            "AnymalC": self._compute_anymalc_reach,
            "PegInsertionSide": self._compute_peg_insertion,
            "PushT": self._compute_push_t,
            "PickCubePandaAllegro": self._compute_pick_cube_allegro,
            "RotateValve": self._compute_rotate_valve,
            "UnitreeG1TransportBox": self._compute_transport_box,
        }[self.task_id]

        # Custom function mode (Eureka)
        self._custom_fn: Optional[Callable] = None
        self._custom_code: Optional[str] = None
        self._custom_fn_error_count = 0
        self._fallback_active = False
        # When True, raise on custom function error instead of falling back
        # to YAML reward. Use True for Eureka mode so the outer loop can
        # detect the failure and retry with LLM-fixed code.
        self._raise_on_custom_fn_error = raise_on_custom_fn_error

    def _component_weight_sum(self) -> float:
        """Sum of non-success weights (used for normalization)."""
        return sum(v for k, v in self.weights.items() if k != "w_success")

    def _norm_scale(self) -> float:
        """Scale factor to keep reward magnitude consistent after weight changes."""
        current_sum = self._component_weight_sum()
        if current_sum < 1e-8:
            return 1.0
        return self._initial_component_sum / current_sum

    def step(self, action):
        obs, _reward, terminated, truncated, info = self.env.step(action)
        reward = self._compute_reward_safe(info)
        info["reward_breakdown"] = self._last_breakdown
        return obs, reward, terminated, truncated, info

    def _compute_reward_safe(self, info: dict) -> torch.Tensor:
        """Execute reward computation with automatic fallback on error."""
        if self._custom_fn is None or self._fallback_active:
            # Use YAML-based reward
            return self._compute_fn(info)

        try:
            base = self.env.unwrapped
            reward = self._custom_fn(info, base)

            # Validate output
            if not isinstance(reward, torch.Tensor):
                raise TypeError(f"Expected torch.Tensor, got {type(reward)}")

            # Shape must be exactly (batch_size,) - 1D tensor
            expected_batch = info["success"].shape[0]
            if reward.ndim != 1:
                raise ValueError(f"Reward must be 1D, got shape {reward.shape}")
            if reward.shape[0] != expected_batch:
                raise ValueError(f"Batch size mismatch: {reward.shape[0]} vs {expected_batch}")

            if not torch.isfinite(reward).all():
                raise ValueError("Reward contains NaN or Inf")

            # Record breakdown for learning curve (Eureka-style feedback).
            # If the custom function wrote per-component data into
            # info["_reward_components"], use that; otherwise record total only.
            self._last_breakdown = {
                "total": reward.mean().item(),
            }
            custom_comps = info.get("_reward_components")
            if isinstance(custom_comps, dict):
                for k, v in custom_comps.items():
                    if isinstance(v, torch.Tensor):
                        self._last_breakdown[k] = v.mean().item()
                    elif isinstance(v, (int, float)):
                        self._last_breakdown[k] = float(v)

            return reward

        except Exception as e:
            self._custom_fn_error_count += 1

            if self._custom_fn_error_count <= 3:
                print(f"[RewardWrapperDynamic] Error in custom function: {e}")
                traceback.print_exc()

            if self._raise_on_custom_fn_error:
                raise RuntimeError(
                    f"Custom reward function failed (error #{self._custom_fn_error_count}): {e}"
                ) from e

            if self._custom_fn_error_count == 1:
                self._fallback_active = True
                print("[RewardWrapperDynamic] Activating YAML fallback")

            return self._compute_fn(info)

    @property
    def is_fallback_active(self) -> bool:
        """True if custom function failed and YAML fallback is in use."""
        return self._fallback_active

    @property
    def custom_fn_error_count(self) -> int:
        """Number of runtime errors encountered in the custom function."""
        return self._custom_fn_error_count

    def get_weights(self) -> Dict[str, float]:
        return dict(self.weights)

    def update_weights(self, new_weights: Dict[str, float]):
        for k, v in new_weights.items():
            if k in self.weights:
                self.weights[k] = v
        print(f"[RewardWrapperDynamic] Updated weights: {self.weights}")

    # === Custom Function Mode (Eureka) ===

    def set_custom_function(
        self,
        custom_fn: Optional[Callable] = None,
        code: Optional[str] = None,
    ) -> bool:
        """
        Replace reward computation with custom function (Eureka mode).

        Args:
            custom_fn: Compiled function (for single env use)
            code: Source code string (for VecEnv distribution)

        Expected signature:
            def compute_reward(info: dict, base) -> torch.Tensor

        Returns:
            True if successfully set
        """
        if custom_fn is None and code is not None:
            custom_fn, error = self._compile_custom_function_with_error(code)
            if custom_fn is None:
                print(f"[RewardWrapperDynamic] Compilation failed: {error}")
                return False

        if custom_fn is None:
            print("[RewardWrapperDynamic] No custom_fn or code provided")
            return False

        self._custom_fn = custom_fn
        self._custom_code = code
        self._custom_fn_error_count = 0
        self._fallback_active = False
        print("[RewardWrapperDynamic] Set custom reward function")
        return True

    def clear_custom_function(self):
        """Revert to YAML-based reward."""
        self._custom_fn = None
        self._custom_code = None
        self._custom_fn_error_count = 0
        self._fallback_active = False
        print("[RewardWrapperDynamic] Cleared custom function, reverted to YAML mode")

    @staticmethod
    def _compile_custom_function_with_error(code: str) -> Tuple[Optional[Callable], Optional[str]]:
        """
        Compile reward function from code string (with error info).

        Args:
            code: Function source code

        Returns:
            (compiled_function, error_message)
            Success: (function, None)
            Failure: (None, error_string)
        """
        import numpy as np

        namespace = {"torch": torch, "np": np, "numpy": np}

        try:
            exec(code, namespace)
        except Exception as e:
            error_msg = f"Compilation error: {type(e).__name__}: {e}\n{traceback.format_exc()}"
            return None, error_msg

        # Search for function (common names)
        for fn_name in ["compute_reward", "reward_fn", "reward", "custom_reward", "custom_term"]:
            if fn_name in namespace and callable(namespace[fn_name]):
                return namespace[fn_name], None

        return None, "Error: No recognizable function name found (need compute_reward, reward_fn, etc.)"

    # --- PickCube ---
    def _compute_pick_cube(self, info: dict) -> torch.Tensor:
        base = self.env.unwrapped
        w = self.weights

        # reach: tcp -> cube distance
        tcp_to_obj_dist = torch.linalg.norm(
            base.cube.pose.p - base.agent.tcp_pose.p, axis=1
        )
        reach_r = 1 - torch.tanh(5 * tcp_to_obj_dist)

        # grasp
        grasp_r = info["is_grasped"].float()

        # place: cube -> goal distance (gated by grasp)
        obj_to_goal_dist = torch.linalg.norm(
            base.goal_site.pose.p - base.cube.pose.p, axis=1
        )
        place_r = (1 - torch.tanh(5 * obj_to_goal_dist)) * grasp_r

        # static: continuous velocity penalty * object placed
        qvel = base.agent.robot.get_qvel()
        if base.robot_uids in ["panda", "widowxai"]:
            qvel = qvel[..., :-2]
        elif base.robot_uids == "so100":
            qvel = qvel[..., :-1]
        static_r = (1 - torch.tanh(5 * torch.linalg.norm(qvel, axis=1))) * info["is_obj_placed"].float()

        scale = self._norm_scale()
        reward = scale * (
            w["w_reach"] * reach_r
            + w["w_grasp"] * grasp_r
            + w["w_place"] * place_r
            + w["w_static"] * static_r
        )
        reward[info["success"]] = w["w_success"]

        self._last_breakdown = {
            "reach": (scale * w["w_reach"] * reach_r).mean().item(),
            "grasp": (scale * w["w_grasp"] * grasp_r).mean().item(),
            "place": (scale * w["w_place"] * place_r).mean().item(),
            "static": (scale * w["w_static"] * static_r).mean().item(),
            "norm_scale": scale,
        }
        return reward

    # --- PickCubePandaAllegro ---
    def _compute_pick_cube_allegro(self, info: dict) -> torch.Tensor:
        base = self.env.unwrapped
        w = self.weights

        # reach: tcp -> cube distance
        tcp_to_obj_dist = torch.linalg.norm(
            base.cube.pose.p - base.agent.tcp_pose.p, axis=1
        )
        reach_r = 1 - torch.tanh(5 * tcp_to_obj_dist)

        # grasp (>=2 fingertips in contact)
        grasp_r = info["is_grasped"].float()

        # place: cube -> goal distance (gated by grasp)
        obj_to_goal_dist = torch.linalg.norm(
            base.goal_site.pose.p - base.cube.pose.p, axis=1
        )
        place_r = (1 - torch.tanh(5 * obj_to_goal_dist)) * grasp_r

        # static: arm velocity penalty (gated by placed)
        qvel = base.agent.robot.get_qvel()[..., :7]  # arm joints only
        static_r = (1 - torch.tanh(5 * torch.linalg.norm(qvel, axis=1))) * info["is_obj_placed"].float()

        scale = self._norm_scale()
        reward = scale * (
            w["w_reach"] * reach_r
            + w["w_grasp"] * grasp_r
            + w["w_place"] * place_r
            + w["w_static"] * static_r
        )
        reward[info["success"]] = w["w_success"]

        self._last_breakdown = {
            "reach": (scale * w["w_reach"] * reach_r).mean().item(),
            "grasp": (scale * w["w_grasp"] * grasp_r).mean().item(),
            "place": (scale * w["w_place"] * place_r).mean().item(),
            "static": (scale * w["w_static"] * static_r).mean().item(),
            "norm_scale": scale,
        }
        return reward

    # --- PushCube ---
    def _compute_push_cube(self, info: dict) -> torch.Tensor:
        base = self.env.unwrapped
        w = self.weights

        # reach: tcp -> push pose (behind the cube)
        push_offset = torch.tensor(
            [-base.cube_half_size - 0.005, 0, 0], device=base.device
        )
        push_pose_p = base.obj.pose.p + push_offset
        tcp_to_push_dist = torch.linalg.norm(
            push_pose_p - base.agent.tcp.pose.p, axis=1
        )
        reach_r = 1 - torch.tanh(5 * tcp_to_push_dist)

        # push: obj xy -> goal xy (gated by reached)
        reached = (tcp_to_push_dist < 0.01).float()
        obj_to_goal_dist = torch.linalg.norm(
            base.obj.pose.p[..., :2] - base.goal_region.pose.p[..., :2], axis=1
        )
        push_r = (1 - torch.tanh(5 * obj_to_goal_dist)) * reached

        # z_keep: keep cube on table (gated by reached)
        z_deviation = torch.abs(base.obj.pose.p[..., 2] - base.cube_half_size)
        z_r = (1 - torch.tanh(5 * z_deviation)) * push_r  # scale with push progress

        scale = self._norm_scale()
        reward = scale * (
            w["w_reach"] * reach_r
            + w["w_push"] * push_r
            + w["w_z_keep"] * z_r
        )
        reward[info["success"]] = w["w_success"]

        self._last_breakdown = {
            "reach": (scale * w["w_reach"] * reach_r).mean().item(),
            "push": (scale * w["w_push"] * push_r).mean().item(),
            "z_keep": (scale * w["w_z_keep"] * z_r).mean().item(),
            "norm_scale": scale,
        }
        return reward

    # --- OpenCabinetDoor / OpenCabinetDrawer ---
    def _compute_open_cabinet(self, info: dict) -> torch.Tensor:
        base = self.env.unwrapped
        w = self.weights

        # reach: tcp -> handle position (already computed by evaluate())
        handle_pos = info["handle_link_pos"]
        tcp_to_handle_dist = torch.linalg.norm(
            base.agent.tcp.pose.p - handle_pos, axis=1
        )
        reach_r = 1 - torch.tanh(5 * tcp_to_handle_dist)

        # open: progress toward target_qpos
        amount_to_open_left = torch.div(
            base.target_qpos - base.handle_link.joint.qpos,
            base.target_qpos,
        )
        open_r = 2 * (1 - amount_to_open_left)
        # if joint opened even a little, replace reach with constant
        reach_r[amount_to_open_left < 0.999] = 2.0

        # static bonus when open enough
        static_r = info["open_enough"].float()

        scale = self._norm_scale()
        reward = scale * (
            w["w_reach"] * reach_r
            + w["w_open"] * open_r
            + w["w_static"] * static_r
        )
        reward[info["success"]] = w["w_success"]

        self._last_breakdown = {
            "reach": (scale * w["w_reach"] * reach_r).mean().item(),
            "open": (scale * w["w_open"] * open_r).mean().item(),
            "static": (scale * w["w_static"] * static_r).mean().item(),
            "norm_scale": scale,
        }
        return reward

    # --- UnitreeG1PlaceAppleInBowl ---
    def _compute_unitree_place_apple(self, info: dict) -> torch.Tensor:
        base = self.env.unwrapped
        w = self.weights

        # reach: tcp -> apple distance
        tcp_to_obj_dist = torch.linalg.norm(
            base.apple.pose.p - base.agent.right_tcp.pose.p, axis=1
        )
        reach_r = 1 - torch.tanh(5 * tcp_to_obj_dist)

        # grasp
        grasp_r = info["is_grasped"].float()

        # place: apple -> bowl distance (gated by grasp)
        obj_to_goal_dist = torch.linalg.norm(
            (base.bowl.pose.p + torch.tensor([0, 0, 0.15], device=base.device))
            - base.apple.pose.p,
            axis=1,
        )
        place_r = (1 - torch.tanh(5 * obj_to_goal_dist)) * grasp_r

        # above_bowl: bonus when apple is close to above-bowl target
        obj_high_above_bowl = obj_to_goal_dist < 0.025
        above_bowl_r = obj_high_above_bowl.float()

        # release: encourage opening hand when above bowl
        grasp_release_reward = 1 - torch.tanh(
            base.agent.right_hand_dist_to_open_grasp()
        )
        release_r = grasp_release_reward * above_bowl_r

        scale = self._norm_scale()
        reward = scale * (
            w["w_reach"] * reach_r
            + w["w_grasp"] * grasp_r
            + w["w_place"] * place_r
            + w["w_above_bowl"] * above_bowl_r
            + w["w_release"] * release_r
        )
        reward[info["success"]] = w["w_success"]

        self._last_breakdown = {
            "reach": (scale * w["w_reach"] * reach_r).mean().item(),
            "grasp": (scale * w["w_grasp"] * grasp_r).mean().item(),
            "place": (scale * w["w_place"] * place_r).mean().item(),
            "above_bowl": (scale * w["w_above_bowl"] * above_bowl_r).mean().item(),
            "release": (scale * w["w_release"] * release_r).mean().item(),
            "norm_scale": scale,
        }
        return reward

    # --- AnymalC-Reach ---
    def _compute_anymalc_reach(self, info: dict) -> torch.Tensor:
        base = self.env.unwrapped
        w = self.weights

        # reach: robot -> goal distance
        robot_to_goal_dist = info["robot_to_goal_dist"]
        reach_r = 1 - torch.tanh(1 * robot_to_goal_dist)

        # penalties
        lin_vel_z_l2 = torch.square(base.agent.robot.root_linear_velocity[:, 2])
        ang_vel_xy_l2 = (
            torch.square(base.agent.robot.root_angular_velocity[:, :2])
        ).sum(axis=1)

        # undesired contacts (knee links hitting ground)
        forces = base.agent.robot.get_net_contact_forces(
            base._UNDESIRED_CONTACT_LINK_NAMES
        )
        contact_penalty = (torch.norm(forces, dim=-1).max(-1).values > 1.0).float()

        # qpos deviation from default standing pose
        qpos_penalty = torch.linalg.norm(
            base.agent.robot.qpos - base.default_qpos, axis=1
        )

        scale = self._norm_scale()
        reward = (
            1.0
            + scale * w["w_reach"] * reach_r
            - w["w_vel_z_penalty"] * lin_vel_z_l2
            - w["w_ang_vel_penalty"] * ang_vel_xy_l2
            - w["w_contact_penalty"] * contact_penalty
            - w["w_qpos_penalty"] * qpos_penalty
        )
        reward[info["fail"]] = 0

        self._last_breakdown = {
            "reach": (scale * w["w_reach"] * reach_r).mean().item(),
            "vel_z_penalty": (w["w_vel_z_penalty"] * lin_vel_z_l2).mean().item(),
            "ang_vel_penalty": (w["w_ang_vel_penalty"] * ang_vel_xy_l2).mean().item(),
            "contact_penalty": (w["w_contact_penalty"] * contact_penalty).mean().item(),
            "qpos_penalty": (w["w_qpos_penalty"] * qpos_penalty).mean().item(),
            "norm_scale": scale,
        }
        return reward

    # --- PegInsertionSide ---
    def _compute_peg_insertion(self, info: dict) -> torch.Tensor:
        base = self.env.unwrapped
        w = self.weights

        # reach: gripper -> peg tail distance
        gripper_pos = base.agent.tcp.pose.p
        offset_pose = base.peg.pose * sapien.Pose([-0.06, 0, 0])
        gripper_to_peg_dist = torch.linalg.norm(
            gripper_pos - offset_pose.p, axis=1
        )
        reach_r = 1 - torch.tanh(4.0 * gripper_to_peg_dist)

        # grasp
        is_grasped = base.agent.is_grasping(base.peg, max_angle=20)
        grasp_r = is_grasped.float()

        # pre-insertion: align peg with hole (yz coordinates)
        peg_head_wrt_goal = base.goal_pose.inv() * base.peg_head_pose
        peg_head_wrt_goal_yz_dist = torch.linalg.norm(
            peg_head_wrt_goal.p[:, 1:], axis=1
        )
        peg_wrt_goal = base.goal_pose.inv() * base.peg.pose
        peg_wrt_goal_yz_dist = torch.linalg.norm(peg_wrt_goal.p[:, 1:], axis=1)

        pre_insertion_r = 1 - torch.tanh(
            0.5 * (peg_head_wrt_goal_yz_dist + peg_wrt_goal_yz_dist)
            + 4.5 * torch.maximum(peg_head_wrt_goal_yz_dist, peg_wrt_goal_yz_dist)
        )

        # insertion: insert peg into hole
        pre_inserted = (peg_head_wrt_goal_yz_dist < 0.01) & (
            peg_wrt_goal_yz_dist < 0.01
        )
        peg_head_wrt_hole = base.box_hole_pose.inv() * base.peg_head_pose
        insertion_r = (
            1 - torch.tanh(5.0 * torch.linalg.norm(peg_head_wrt_hole.p, axis=1))
        ) * (is_grasped & pre_inserted).float()

        scale = self._norm_scale()
        reward = scale * (
            w["w_reach"] * reach_r
            + w["w_grasp"] * grasp_r
            + w["w_pre_insertion"] * pre_insertion_r * grasp_r
            + w["w_insertion"] * insertion_r
        )
        reward[info["success"]] = w["w_success"]

        self._last_breakdown = {
            "reach": (scale * w["w_reach"] * reach_r).mean().item(),
            "grasp": (scale * w["w_grasp"] * grasp_r).mean().item(),
            "pre_insertion": (scale * w["w_pre_insertion"] * pre_insertion_r * grasp_r).mean().item(),
            "insertion": (scale * w["w_insertion"] * insertion_r).mean().item(),
            "norm_scale": scale,
        }
        return reward

    # --- PushT ---
    def _compute_push_t(self, info: dict) -> torch.Tensor:
        base = self.env.unwrapped
        w = self.weights

        # rotation alignment: cos similarity between tee and goal rotation
        tee_z_eulers = base.quat_to_z_euler(base.tee.pose.q)
        rot_rew = (tee_z_eulers - base.goal_z_rot).cos()
        rotation_r = ((rot_rew + 1) / 2) ** 2

        # position alignment: tee xy -> goal xy distance
        tee_to_goal_pose = base.tee.pose.p[:, 0:2] - base.goal_tee.pose.p[:, 0:2]
        tee_to_goal_dist = torch.linalg.norm(tee_to_goal_pose, axis=1)
        position_r = (1 - torch.tanh(5 * tee_to_goal_dist)) ** 2

        # tcp guidance: encourage end-effector to stay near tee
        tcp_to_tee = base.tee.pose.p - base.agent.tcp.pose.p
        tcp_to_tee_dist = torch.linalg.norm(tcp_to_tee, axis=1)
        tcp_guide_r = (1 - torch.tanh(5 * tcp_to_tee_dist)).sqrt()

        scale = self._norm_scale()
        reward = scale * (
            w["w_rotation"] * rotation_r
            + w["w_position"] * position_r
            + w["w_tcp_guide"] * tcp_guide_r
        )
        reward[info["success"]] = w["w_success"]

        self._last_breakdown = {
            "rotation": (scale * w["w_rotation"] * rotation_r).mean().item(),
            "position": (scale * w["w_position"] * position_r).mean().item(),
            "tcp_guide": (scale * w["w_tcp_guide"] * tcp_guide_r).mean().item(),
            "norm_scale": scale,
        }
        return reward

    # --- RotateValve ---
    def _compute_rotate_valve(self, info: dict) -> torch.Tensor:
        base = self.env.unwrapped
        w = self.weights

        # contact: fingertip distance to ideal contact circle on valve
        tip_poses = base.agent.tip_poses  # (b, 3, 7)
        tip_pos = tip_poses[:, :, :2]  # (b, 3, 2)
        valve_pos = base.valve_link.pose.p[:, :2]  # (b, 2)
        valve_tip_dist = torch.linalg.norm(tip_pos - valve_pos[:, None, :], dim=-1)
        desired_dist = base.capsule_lens[:, None] - base.capsule_offset
        error = torch.norm(valve_tip_dist - desired_dist, dim=-1)
        contact_r = 1 - torch.tanh(error * 10)

        # velocity: directed rotation velocity
        directed_vel = base.valve.qvel[:, 0] * base.rotate_direction
        velocity_r = torch.tanh(5 * directed_vel)

        # progress: cumulative rotation toward goal
        rotation = info["valve_rotation"]
        progress_r = torch.clip(rotation * base.rotate_direction / (torch.pi / 2), -1, 1)

        scale = self._norm_scale()
        reward = scale * (
            w["w_contact"] * contact_r
            + w["w_velocity"] * velocity_r
            + w["w_progress"] * progress_r
        )

        self._last_breakdown = {
            "contact": (scale * w["w_contact"] * contact_r).mean().item(),
            "velocity": (scale * w["w_velocity"] * velocity_r).mean().item(),
            "progress": (scale * w["w_progress"] * progress_r).mean().item(),
            "norm_scale": scale,
        }
        return reward

    # --- UnitreeG1TransportBox ---
    def _compute_transport_box(self, info: dict) -> torch.Tensor:
        base = self.env.unwrapped
        w = self.weights

        # Stage 1: face the box (turn torso toward table 1)
        face_box_r = 1 - torch.tanh((base.agent.robot.qpos[:, 0] + 1.4).abs())

        # Stage 2: grasp - arms down + TCPs near box grasp points
        arm_down_r = (
            (1 - torch.tanh(base.agent.robot.qpos[:, 3].abs())) / 4
            + (1 - torch.tanh(base.agent.robot.qpos[:, 4].abs())) / 4
        )
        right_tcp_dist = torch.linalg.norm(
            base.agent.right_tcp.pose.p - base.box_right_grasp_point.p, dim=1
        )
        left_tcp_dist = torch.linalg.norm(
            base.agent.left_tcp.pose.p - base.box_left_grasp_point.p, dim=1
        )
        tcp_r = (
            (1 - torch.tanh(3 * right_tcp_dist)) / 4
            + (1 - torch.tanh(3 * left_tcp_dist)) / 4
        )
        grasp_r = (1 + arm_down_r + tcp_r)
        # Only count grasp reward when facing box
        grasp_r = torch.where(info["facing_table_with_box"], grasp_r, torch.zeros_like(grasp_r))

        # Stage 3: transport - turn toward table 2 while grasping
        turn_r = 1 - torch.tanh((base.agent.robot.qpos[:, 0] - 1.4).abs() / 5)
        transport_r = (2 + turn_r)
        transport_r = torch.where(info["box_grasped"], transport_r, torch.zeros_like(transport_r))

        # Stage 4: release - raise arms to let go
        arm_up_r = (
            (1 - torch.tanh((base.agent.robot.qpos[:, 3] - 1.25).abs())) / 2
            + (1 - torch.tanh((base.agent.robot.qpos[:, 4] + 1.25).abs())) / 2
        )
        release_r = (3 + arm_up_r)
        release_r = torch.where(info["box_at_correct_table_xy"], release_r, torch.zeros_like(release_r))

        scale = self._norm_scale()
        # Staged reward: take the highest active stage
        reward = scale * torch.max(
            torch.max(
                torch.max(
                    w["w_face_box"] * face_box_r,
                    w["w_grasp"] * grasp_r,
                ),
                w["w_transport"] * transport_r,
            ),
            w["w_release"] * release_r,
        )
        reward[info["success"]] = w["w_success"]

        self._last_breakdown = {
            "face_box": (scale * w["w_face_box"] * face_box_r).mean().item(),
            "grasp": (scale * w["w_grasp"] * grasp_r).mean().item(),
            "transport": (scale * w["w_transport"] * transport_r).mean().item(),
            "release": (scale * w["w_release"] * release_r).mean().item(),
            "norm_scale": scale,
        }
        return reward
